import type { Difficulty, Question, QuestionOption, Topic } from "../types/question";

export type OptionId = QuestionOption["id"];
export const EXAM_ID = "FS23";
export const EXAM_LABEL = "FS23 · August 2023";
export const opts = (...items: Array<[OptionId, string]>): QuestionOption[] => items.map(([id, text]) => ({ id, text }));

export function q({ number, points, title, prompt, options, correct, topic, difficulty, setup, multipleSelect = false, figureNumber, figureAlt, figureCaption, explanation }: {
  number: number; points: number; title: string; prompt: string; options: QuestionOption[]; correct: OptionId[];
  topic: Topic; difficulty: Difficulty; setup?: string; multipleSelect?: boolean; figureNumber?: number; figureAlt?: string; figureCaption?: string; explanation: string;
}): Question {
  return {
    id: `fs23-q${String(number).padStart(2, "0")}`, examId: EXAM_ID, examLabel: EXAM_LABEL, number, title, setup, prompt, options,
    correctOptionId: correct[0], correctOptionIds: correct, multipleSelect, explanation, topic, difficulty,
    source: `FS23 · Question ${number} · ${points} point${points === 1 ? "" : "s"} · answer derived (source exam has no solution key)`,
    figureNumber, figureAlt, figureCaption,
  };
}

export const MODEL_CAPACITY_SETUP = "Consider a dataset $\\{(x_1,y_1),\\ldots,(x_n,y_n)\\}$, where $x_i,y_i\\in\\mathbb{R}$ and all $x_i$ are distinct. Consider kernel regression with kernel $k:\\mathbb{R}\\times\\mathbb{R}\\to\\mathbb{R}$ where we search for a model of the form $f(x)=\\sum_{i=1}^n a_i k(x_i,x)$ where the coefficients $a_1,\\ldots,a_n$ are learned from the dataset.";

export const KRR_FIGURE_SETUP = "Consider a dataset $\\{(x_1,y_1),\\ldots,(x_n,y_n)\\}$, where $x_i,y_i\\in\\mathbb{R}$. We perform kernel ridge regression on this dataset and consider different choices for the kernel function. For all the choices, we use the same regularization coefficient $\\lambda>0$. Figure 1 shows the results: the curves are the learned models, and the dots show the data (which is the same across all 4 plots). Match the plots to the corresponding kernels.\n\nThe kernels used are\n• the linear kernel $k_1(x,x')=xx'$,\n• the quadratic kernel $k_2(x,x')=(1+xx')^2$,\n• the RBF kernel $k_3(x,x')=e^{-|x-x'|^2/l_1^2}$ with a small length scale $l_1$,\n• the RBF kernel $k_4(x,x')=e^{-|x-x'|^2/l_2^2}$ with a large length scale $l_2$ (such that $l_2>l_1$).";

export const NN_GENERAL_SETUP = "We consider a fully-connected neural network with $L>1$ layers and elementwise ReLU activation functions $h(z):=\\max(z,0)$, where the derivative at zero is defined as $h'(0):=0$. For simplicity, our neural network has no bias terms. The weight matrix of layer $k\\in\\{1,\\ldots,L\\}$ is $W^{(k)}\\in\\mathbb{R}^{q_k\\times p_k}$. We define\n$$v^{(k)}:=h(W^{(k)}v^{(k-1)})\\in\\mathbb{R}^{q_k},\\quad 1\\leq k\\leq L-1,\\qquad v^{(0)}:=x,$$\nand\n$$f(x,W):=W^{(L)}v^{(L-1)}.$$\nThe network has scalar-valued outputs $f(x,W)\\in\\mathbb{R}$, i.e. $q_L=1$.";

export const NN_BACKPROP_SETUP = `${NN_GENERAL_SETUP}\n\nFor Questions 14–15, we use the squared loss $\\ell$. Given a target value $y\\in\\mathbb{R}$,\n$$\\ell(x,y,W)=(y-f(x,W))^2.$$\nWe use backpropagation to compute the parameter gradients $\\nabla_{W^{(k)}}\\ell(x,y,W)$.`;

export const NN_INIT_SETUP = `${NN_GENERAL_SETUP}\n\nIn Questions 16–19, we experiment with different initialization schemes for the network weights $W$. Recall that the network uses elementwise ReLU activations with $h'(0)=0$.`;

export const TRAIN_TEST_SETUP = "Suppose a dataset $D=\\{(x_i,y_i)\\}_{i=1}^n$ contains a small to moderate number of i.i.d. samples from some distribution $P$. The dataset $D$ is randomly split into a train and test set. A machine learning method is then applied on the train set to obtain a predictive model that incurs a training error (prediction error on the train set) and test error (prediction error on the test set).";

export const CV_SETUP = "Suppose a dataset $D=\\{(x_i,y_i)\\}_{i=1}^n$ contains a small to moderate number of i.i.d. samples from some distribution $P$. Consider cross-validation (CV) for choosing the regularization coefficient $\\lambda$ of ridge regression. Let $\\hat f_\\lambda$ be obtained by minimizing the ridge regression loss on $D$ with regularization coefficient $\\lambda$, and let $L(f;P):=\\mathbb{E}_{(x,y)\\sim P}[(f(x)-y)^2]$ denote true generalization error. We perform $K$-fold cross-validation and compute $CV_K(\\lambda)$. Figure 2 shows the CV errors for $K_i\\in\\{2,5,20\\}$, $i=1,2,3$, and $\\lambda\\in[10^{-2},10^2]$.";

export const REGULARIZATION_SETUP = "We have training data $D=\\{(x_i,y_i)\\}_{i=1}^n$ with $x_i\\in\\mathbb{R}^d$, $y_i\\in\\mathbb{R}$ and $n>d$, generated by $y=Xw^\\star+\\varepsilon$, where $X\\in\\mathbb{R}^{n\\times d}$ is full-rank and $\\varepsilon_i\\sim\\mathcal{N}(0,\\sigma^2)$ i.i.d. We consider\n$$\\hat w^{LS}:=\\arg\\min_w\\|y-Xw\\|_2^2,$$\n$$\\hat w^{BS}:=\\arg\\min_{\\|w\\|_0=k}\\|y-Xw\\|_2^2,$$\n$$\\hat w^{lasso}(\\lambda):=\\arg\\min_w\\|y-Xw\\|_2^2+\\lambda\\|w\\|_1,$$\n$$\\hat w^{ridge}(\\lambda):=\\arg\\min_w\\|y-Xw\\|_2^2+\\lambda\\|w\\|_2^2,\\qquad \\lambda>0.$$";
export const REGULARIZATION_ORTHO_SETUP = `${REGULARIZATION_SETUP}\n\nImportant: For Questions 25–29, assume that $X^\\top X=I$.`;

export const KMEANS_SETUP = "Given a dataset $D=\\{x_1,\\ldots,x_n\\}$ of size $n=1000$ with $x_i\\in\\mathbb{R}^d$, the $K$-means problem aims to find\n$$C^*=\\arg\\min_{C=\\{\\mu_1,\\ldots,\\mu_K\\}}R(C),\\qquad R(C)=\\sum_{x_i\\in D}\\min_{z_i}\\|x_i-\\mu_{z_i}\\|_2^2,$$\nwhere $z_i\\in\\{1,\\ldots,K\\}$ and $K\\geq2$. We consider Lloyd's algorithm and assume it terminates once $R(C)$ did not improve for one iteration.";

export const COFFEE_SETUP = "We want to model lifetimes of coffee machines. We observe $n$ independent lifetimes $D=\\{x_1,\\ldots,x_n\\}$, where $x_i\\sim\\operatorname{Exp}(\\theta)$ and $\\theta>0$. For $x\\sim\\operatorname{Exp}(\\theta)$, $p(x;\\theta)=\\theta e^{-\\theta x}I(\\{x\\geq0\\})$.";

export const CUSTOMER_SETUP = "You want to group customers into three clusters based on their purchases, using soft EM. Each customer belongs to one of three clusters $Y\\in\\{1,2,3\\}$ with unknown $P(Y=k)=p_k$. Each customer has purchase vector $X\\in\\{0,1\\}^5$, and conditional on $Y$, the five Bernoulli purchase variables are independent with unknown probabilities $P(X_i=1\\mid Y=k)$. We estimate $p_1,p_2,p_3$ and all conditional purchase probabilities using soft EM.\n\nObserved customers are\n$$x_1=(0,1,1,0,0),\\qquad x_2=(0,0,1,0,1),\\qquad x_3=(0,0,0,1,0).$$\nInitialize $p_1=p_2=p_3=1/3$ and\n$$\\begin{array}{c|ccccc}&X_1&X_2&X_3&X_4&X_5\\\\\\hline Y=1&1/3&1/3&1/3&0&0\\\\Y=2&0&0&1/2&1/2&1/4\\\\Y=3&3/4&0&1/2&1/2&1/2\\end{array}.$$";

export const DERIVED = "Derived answer (the supplied FS23 question pack contains no official solution key): ";
